name 'meanmaster'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures meanmaster'
long_description 'Installs/Configures meanmaster'
version '0.1.0'
